import { expect, test } from '@playwright/test'

// 1x1 PNG; the gateway decodes and re-encodes it.
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC', 'base64')

test('demo: login → project → profile → key → playground → photo analysis → usage', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('tab', { name: 'Kayıt ol' }).click()
  await page.getByLabel('E-posta').fill(`e2e-${Date.now()}@example.test`)
  await page.getByLabel('Parola').fill('Correct-horse-9')
  await page.getByLabel('Workspace adı').fill('E2E')
  await page.getByRole('button', { name: 'Hesap oluştur' }).click()
  await expect(page.getByRole('heading', { name: 'Genel bakış' })).toBeVisible()
  await expect(page.getByRole('note').filter({ hasText: 'DEMO modu' })).toBeVisible()

  await page.getByRole('link', { name: 'Projeler' }).click()
  await page.getByRole('button', { name: 'Yeni proje' }).click()
  await page.getByLabel('Proje adı').fill('Fitness App')
  await page.getByRole('button', { name: 'Oluştur' }).click()
  await expect(page.getByRole('cell', { name: 'Fitness App' })).toBeVisible()

  await page.getByRole('link', { name: 'Profiller' }).click()
  await page.getByRole('button', { name: 'Yeni profil' }).click()
  await page.getByLabel('Profil adı').fill('workout-extraction')
  await page.getByRole('button', { name: 'Oluştur' }).click()
  await page.getByRole('button', { name: 'Yeni revizyon' }).click()
  await page.getByLabel('Birincil model').selectOption('demo/demo-model')
  await page.getByLabel('Görsel').check()
  await page.getByLabel('JSON Schema').check()
  await page.getByRole('button', { name: 'Revizyonu kaydet' }).click()
  await page.getByLabel('Fitness App/development:').selectOption({ label: 'Rev #1' })
  await expect(page.getByText('Yayında')).toBeVisible()

  await page.getByRole('link', { name: 'API anahtarları' }).click()
  await page.getByRole('button', { name: 'Yeni anahtar' }).click()
  await page.getByLabel('Ad', { exact: true }).fill('backend')
  await page.getByRole('button', { name: 'Oluştur' }).click()
  await expect(page.getByLabel('API anahtarı', { exact: true })).toHaveValue(/^pgw_/)
  await page.getByRole('button', { name: 'Kaydettim, kapat' }).click()
  await expect(page.getByRole('cell', { name: 'backend' })).toBeVisible()

  await page.getByRole('link', { name: 'Playground' }).click()
  await page.getByLabel('Mesaj', { exact: true }).fill('Merhaba gateway')
  await page.getByRole('button', { name: 'Gönder' }).click()
  await expect(page.locator('pre')).toContainText('DEMO yanıtı')
  await expect(page.getByText(/maliyet: bilinmiyor/)).toBeVisible()

  await page.getByRole('link', { name: 'Antrenman içe aktarma' }).click()
  await expect(page.getByRole('heading', { name: 'Antrenman içe aktarma' })).toBeVisible()
  await page.locator('input[type=file]').setInputFiles({ name: 'program.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('img', { name: 'program.png' })).toBeVisible()
  await page.getByRole('button', { name: 'Programı çıkar' }).click()
  await expect(page.getByText('DEMO: çıktı gerçek görselden okunmadı.')).toBeVisible()
  await page.getByLabel('Program adı').fill('Haftalık plan')
  await page.getByRole('button', { name: 'Gün ekle' }).click()
  await page.getByLabel('Gün 1', { exact: true }).fill('Pazartesi')
  await page.getByLabel('Programı görselle karşılaştırdım ve düzelttim.').check()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'JSON indir' }).click()
  const program = JSON.parse(await (await (await download).createReadStream()).toArray().then((c) => Buffer.concat(c).toString()))
  expect(program).toMatchObject({ title: 'Haftalık plan', days: [{ name: 'Pazartesi', exercises: [] }] })

  await page.getByRole('link', { name: 'Kullanım' }).click()
  await expect(page.getByRole('cell', { name: 'workout-import' })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'playground' })).toBeVisible()
  await page.getByRole('cell', { name: 'workout-import' }).click()
  await expect(page.getByRole('dialog', { name: 'İstek detayı' })).toContainText('demo/demo-model')
})
